### ISSUE TITLE
Lỗi UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-2: character maps to <undefined> 

### ISSUE THREAD

**Issue by tanthinhdt** [v-nhandt21/Viphoneme#4]
Chào anh, khi em chạy thử các ví dụ của anh trong readme hoặc chạy trên dữ liệu của em đều gặp lỗi này. Em đã kiểm tra chắc chắn cài đặt đầy đủ các thư viện. Anh có thể hướng dẫn em khắc phục lỗi này với ạ. Em xin cảm ơn

**Comment by v-nhandt21** [comment]
> Chào anh, khi em chạy thử các ví dụ của anh trong readme hoặc chạy trên dữ liệu của em đều gặp lỗi này. Em đã kiểm tra chắc chắn cài đặt đầy đủ các thư viện. Anh có thể hướng dẫn em khắc phục lỗi này với ạ. Em xin cảm ơn

À hình như em chạy bằng Window đúng không em, cái này nó chỉ sử dụng ở linux thôi á em, hihi

**Comment by tanthinhdt** [comment]
À thì ra là vậy. Em cảm ơn anh ạ
